### ISSUE TITLE
STATEWIDE_PRECINCT_SORT.txt

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/pdv-nc#1]
@DavidAndrewsNH, [VEST's metadata](https://redistrictingdatahub.org/wp-content/uploads/2021/06/readme_nc_vest_20.txt) refers to "precinct-sorted results".  But I don't see that source file read into nc_vest_2020.ipynb.

**Comment by DavidAndrewsNH** [comment]
Sorry I should have made it more clear but it's right below the file read for the election results. It's listed as the county results.
