### ISSUE TITLE
asterisk in VEST's metadata for nc_vest_2020.ipynb

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/pdv-nc#3]
@DavidAndrewsNH  In [VEST's metadata](https://redistrictingdatahub.org/wp-content/uploads/2021/06/readme_nc_vest_20.txt), the Processing Steps described: 
> In counties marked by asterisk, some votes were still reported by vote center or countywide in the precinct-sorted data. These were distributed by candidate to precincts based on the precinct-level reported vote.

Among the counties marked by asterisk is Mecklenburg, which has a value of '119' in vest_shp['COUNTYFP10'].  Among the counties WITHOUT an asterisk is Martin, which has a value of '117' in vest_shp['COUNTYFP10'].
### Problem:
In cell Out[31], your output is:
![image](https://user-images.githubusercontent.com/22034168/141024581-8bfe4987-5fb1-4214-8ea6-6f0983a57823.png)
The first non-bolded column is in_sos['COUNTYFP10'].  The upper row is Martin, and the lower row is Mecklenburg.  The upper row has non-zero votes in the rest of its columns, while the lower row has only zeros.

So the upper row has some votes that "were still reported by vote center or countywide in the precinct-sorted data".  In contrast, the lower row has no such votes.  Therefore, VEST's metadata should have marked an asterisk next to "Martin" rather than next to "Mecklenburg".
### Question:
Which of the following explanations is true?
1. vest_shp didn't redistribute votes that were still reported by vote center or countywide in the precinct-sorted data for Martin county.  Hence, both vest_shp and VEST's metadata are incorrect.
2. VEST's metadata just made a typo, and the processing steps were correctly performed in vest_shp for both counties.  Hence, only VEST's metadata needs to be corrected.

**Comment by DavidAndrewsNH** [comment]
I'm not 100% sure but I would guess that it was a simple typo since VEST's county results match the official results from the NC State Board of Elections.

**Comment by rootsmusic** [comment]
I appreciate you taking a look at this issue.  If the first explanation is true, then this issue would have affected the allocation of precinct-level results for Martin county (not count-level).  I'm leaving this issue open, in case someone else figures out how to validate VEST's precinct-level results.
